import React from 'react'
import Contact from './contact'
import ServerComponent from '@/component/servers/ServerComponent';

export const metadata = {
  title: 'Contact',
  description: 'Generated by Newbie',
}

const page = () => {
  return (
    <Contact value={"Nice"}>
    <ServerComponent/>
    </Contact>
  )
}

export default page;



