import React from 'react'

export const metadata = {
    title: 'About',
    description: 'Generated by Newbie',
  }

const page = () => {
  return (
    <div>
      <h1>About</h1>
    </div>
  )
}

export default page
