import Header from './header'
import '../styles/globals.css'

export const metadata = {
  title: 'NextJS IS fired',
  description: 'Generated by Newbie',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
 
      <body>
      <Header/>
      {children}
      
      
      
      </body>
    </html>
  )
}
